<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://github.com/PEDSnet/DQResults_MAP"
           xmlns:vocab="https://github.com/PEDSnet/DQResults_MAP/tree/main/schema/local_vocabularies">

  <xs:simpleType name="DQEvalVocabulary">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Study Infeasible"/>
      <xs:enumeration value="Study Design Revised"/>
      <xs:enumeration value="Study Variable Modified"/>
      <xs:enumeration value="Attrition Criteria Modified"/>
      <xs:enumeration value="Investigation Dates Modified"/>
      <xs:enumeration value="Concept Sets Refined"/>
      <xs:enumeration value="Study Methods Revised"/>
      <xs:enumeration value="Data Source Adjusted"/>
      <xs:enumeration value="Site Intervention"/>
      <xs:enumeration value="Coordinating Center Intervention"/>
      <xs:enumeration value="Additional DQ Investigation"/>
      <xs:enumeration value="No Intervention"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
