<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://pedsnet.github.io/DQResults_MAP/"
           xmlns:vocab="https://pedsnet.github.io/DQResults_MAP/schema/local_vocabularies/vocab-dqeval.xsd">

  <xs:simpleType name="DQEval">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Person-Level Analysis"/>
      <xs:enumeration value="Visit-Level Analysis"/>
      <xs:enumeration value="Event-Level Analysis"/>
      <xs:enumeration value="Longitudinal Analysis"/>
      <xs:enumeration value="Cross-Sectional Analysis"/>
      <xs:enumeration value="Multi-Site Analysis"/>
      <xs:enumeration value="Single-Site Analysis"/>
      <xs:enumeration value="Data Anomaly Method"/>
      <xs:enumeration value="Exploratory Analysis"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>