<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://pedsnet.org/metadata/admin/registries/metadata/local/vocab"
           xmlns:vocab="https://pedsnet.org/metadata/admin/registries/metadata/local/vocab">

  <xs:simpleType name="DQEvalVocabulary">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Person-Level Analysis"/>
      <xs:enumeration value="Visit-Level Analysis"/>
      <xs:enumeration value="Event-Level Analysis"/>
      <xs:enumeration value="Longitudinal Analysis"/>
      <xs:enumeration value="Cross-Sectional Analysis"/>
      <xs:enumeration value="Multi-Site Analysis"/>
      <xs:enumeration value="Single-Site Analysis"/>
      <xs:enumeration value="Data Anomaly Method"/>
      <xs:enumeration value="Exploratory Analysis"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>